In [3]:
import pandas as pd
import numpy as np
import gensim
from gensim.models import Word2Vec
from GensimWord2Vec import GensimWord2VecVectorizer as word2vec

In [4]:
messages = pd.read_csv('preprocessed.csv')
messages = messages.drop(labels = ['Unnamed: 0'], axis=1)
messages['clean message'] = messages['Commit message'].apply(lambda x: x.split())
messages.head()

,Commit message,Class,clean message
0,extract method,extract,"[extract, method]"
1,minor tweak follow review extraction method pl...,extract,"[minor, tweak, follow, review, extraction, met..."
2,extract stuff method git p depot path coremedi...,extract,"[extract, stuff, method, git, p, depot, path, ..."
3,extract method doiserviceimpl,extract,"[extract, method, doiserviceimpl]"
4,refactoring getmenuspace navigation extract is...,extract,"[refactoring, getmenuspace, navigation, extrac..."

In [18]:
extract = messages.loc[messages['Class']=='extract']
extract_w2v = Word2Vec(extract['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(extract_w2v.wv.most_similar('extract'))

            0         1
0       logic  0.880080
1        move  0.863728
2     package  0.860011
3      method  0.857607
4    tutorial  0.850177
5    creation  0.845054
6       major  0.834755
7        make  0.830124
8       start  0.826906
9  additional  0.821770

In [19]:
inline = messages.loc[messages['Class']=='inline']
inline_w2v = Word2Vec(inline['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(inline_w2v.wv.most_similar('inline'))

           0         1
0     render  0.897131
1      leave  0.880169
2    setting  0.837293
3      range  0.822391
4    inlined  0.816516
5  selection  0.800166
6     single  0.786232
7     extend  0.785375
8    declare  0.782975
9  redundant  0.775125

In [20]:
move = messages.loc[messages['Class']=='move']
move_w2v = Word2Vec(move['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(move_w2v.wv.most_similar('move'))

          0         1
0    ashish  0.810485
1       doc  0.807353
2     class  0.806138
3  optional  0.805838
4   package  0.795078
5  constant  0.789111
6   content  0.788566
7     major  0.787490
8   release  0.784661
9   cleanup  0.784479

In [21]:
pull_up = messages.loc[messages['Class']=='pull up']
pull_up_w2v = Word2Vec(pull_up['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(pull_up_w2v.wv.most_similar('pull'))

          0         1
0    common  0.852906
1   summary  0.835756
2     scope  0.834714
3      push  0.818586
4     clean  0.813324
5  refactor  0.812666
6  executor  0.811024
7     share  0.787206
8   library  0.785531
9      back  0.780668

In [22]:
push_down = messages.loc[messages['Class']=='push down']
push_down_w2v = Word2Vec(push_down['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(push_down_w2v.wv.most_similar('push'))

          0         1
0   cleanup  0.870298
1   various  0.863890
2     inner  0.859695
3    future  0.853019
4     stuff  0.835935
5  progress  0.822510
6       map  0.821545
7      also  0.815871
8     could  0.813642
9         n  0.811617

In [23]:
rename = messages.loc[messages['Class']=='rename']
rename_w2v = Word2Vec(rename['clean message'],vector_size=750, window=5, epochs=10, hs=1, sg=1)
pd.DataFrame(rename_w2v.wv.most_similar('rename'))

             0         1
0   convention  0.907791
1        clean  0.901623
2        match  0.896453
3  terminology  0.871399
4   constraint  0.871199
5    signature  0.869900
6       option  0.868924
7    condition  0.868483
8       ensure  0.867577
9      content  0.866109